### ISSUE TITLE
배포자동화 절차

### ISSUE THREAD

**Issue by skarltjr** [skarltjr/Memory_Write_Record#15]

**Comment by skarltjr** [comment]
### 스트레스 테스트 툴로 성능테스트하기
- node : artillery 
- vscode사용 
- npm install로 artillery다운로드 
- 34.64.70.44 = vm 외부 ip  = 테스트하고자하는 
```
config:
  target: "http://34.64.70.44"
  phases:
    - duration: 60
      arrivalRate: 1
      name: Warm up
scenarios:
  # We define one scenario:
  - name: "just get hash"
    flow:
      - get:
          url: "/hash/123"
```

**Comment by skarltjr** [comment]
## Nginx 무중단 배포
- gcp 워커인스턴스를 3개 다 만드는게 아니라 gcp가 제공해주는 기능 . 복사
- 머신 이미지 -> 머신이미지 만들기
![화면 캡처 2021-02-07 153115](https://user-images.githubusercontent.com/62214428/107138760-8a67db00-6959-11eb-9a2a-50fbe7ec4015.png)

- 이렇게 만들어진 인스턴스는 모두 기존 워커인스턴스와 동일한 환경을 갖는다.  여기서 동일하다는 것은 파일에 대한내용. 설치해준 패키지나 다운로드한것들이 동일한것이지 젠킨스 배포관련설정,8080 포트띄워준 도커 애플리케이션은 해당 x

**Comment by skarltjr** [comment]
## GithubWebhook과 jenkins를 통한 배포자동화
- 나의 저장소이거나 저장소를 fork해서 push/webhook설정 권한획득
- 젠킨스에 접속하여 프로젝트(아이템)
-> 구성
-> 소스코드 관리 Git체크
-> 저장소 Url추가
-> Build에서 Excute shell
-깃허브에서 변경사항을 체크하고 다시 패키징을 통해 생성된 jar파일을 배포
-배포를 위해선 메이븐 clean / packing을 통해 타겟디렉토리clean/ 변경사항을 포함하여 다시 패키징을 통해 jar파일 생성
-메이븐 mvnw활용 
-

**Comment by skarltjr** [comment]
## DB I/O bound Application
- postgresql 인스턴스를 하나 더 생성
- 이 때 yml / properties에서 로컬에서 db를 사용할 땐 `spring.datasource.url=jdbc:postgresql://localhost:5432/testdb `이었지만
- 인스턴스 내부에서 db를 실행하기위해  postgresql인스턴스 내부아이피로 localhost를 변경
![화면 캡처 2021-02-10 152855](https://user-images.githubusercontent.com/62214428/107473868-b4690980-6bb4-11eb-8c67-4af2c2635835.png)
`sudo yum install docker ` // 도커설치 
`sudo systemctl start docker ` // 도커데몬 실행
`sudo chmod 666 /var/run/docker.sock` // 권한부여
`docker run --name pgsql -d -p 5432:5432 -e POSTGRES_USER=postgresql -e POSTGRES_PASSWORD=postgrespassword postgres` // 도커로 psql실행

- iobound app을 위한 워커인스턴스를 따로 또 만들어서 할 수 있지만 여기서는 기존의 cpu -worker인스턴스 재사용
- ★대신 젠킨스에서 새로운 배포 아이템을 만들기
- 이 때 기존 cpu-bound application deploy아이템을 복사하여 생성할 수 있는데 (어차피 배포과정은 jar파일 clean packing을 통해 동일하게 진행할것이기 때문에)
- 새로운 아이템에서
![화면 캡처 2021-02-10 155015](https://user-images.githubusercontent.com/62214428/107475577-b4b6d400-6bb7-11eb-892c-e4c1c70907e4.png)

**Comment by skarltjr** [comment]
## I/O Bound - 깃 플로우를 통해 기능개발
- 페이징기능을 위해 sourcetree에서 깃플로우로 paging브랜치 따기(깃플로우 기능개발시작)
- 여기서는 현재` url: jdbc:postgresql://10.140.0.3:5432/postgresql` 이지만 로컬에서 개발을 위해 주석처리 후 localhost로 변경해서사용
- 실제로는 properties파일을 통해 @Profile을 나눠서하기  
- 간단한 페이징 기능 추가 
```
   @GetMapping("/posts")
    public Page<Post> getPostList(@PageableDefault(size = 20, sort = "id", direction = Sort.Direction.DESC) Pageable pageable) {
        return postRepository.findAll(pageable);
    }
```
- 커밋 : 이 때 여기서 yml or properties에서 url변경 된 파일은 커밋스테이지에 올리면 안된다. 기능개발 종료 대신 PR로 수행하기
- 푸쉬 : dev와 feat:paging push( 깃허브에서 확인 후 pr로 merge하기)
- pr시 base repository는 나의 레퍼지토리 /  feat -> dev로 
- 변경사항 반영을 위해 sourcetree에서 feat pull당기기 
![화면 캡처 2021-02-11 152222](https://user-images.githubusercontent.com/62214428/107607580-fbbacd00-6c7c-11eb-8ffd-a4a0acb9008d.png)
- origin dev와 로컬 dev가 다른것을 확인할 수 있다. - dev도 pull
--------------- 다음기능 개발 
- 다음으로 개발해야 할 글 번호로 조회하기를 위해 새 기능 브랜치따기(find-by-id)
- 동일하게 개발 후커밋하고  find-by-id브랜치 push  / dev는 이전에 이미 push해서 올려놨다.
- pr 후 find-by-id pull
- 동일하게 origin dev와 로컬 dev가 다른것 확인 후 dev도 pull
--------------- 마지막으로 기능 추가
- dev브랜치에서 find-by-content브랜치따고
- content를 포함한 content를 가진 post 리스트로 반환기능 추가
```
   @GetMapping("/search")
    public List<Post> findPostsByContent(@RequestParam String content) {
        return postRepository.findByContentContains(content);
    }
```
- find-by-content브랜치에서 커밋 후 push
- pr 후 pulll 
- dev도 pull받아서 맞춰주기

--------------
- 마지막으로 main에 합쳐주기 merge
- 메인브랜치에서 병합 
- 이 후 push

이제 이 변경사항을 젠킨스를 통해 배포하기

**Comment by skarltjr** [comment]
## RabbitMQ : message Queue★
- 서버가 죽는 이유? : 톰캣은 들어오는 요청을 큐에 저장하고 놀고있는 스레드가 있으면 이를 보내서 처리하는데 만약 요청이 너무많아 큐에 저장할수조차 없다면 서버가 죽는다 or 처리되는 시간이 30초 이상인경우 timeout
![화면 캡처 2021-02-13 143120](https://user-images.githubusercontent.com/62214428/107842639-30a75b00-6e08-11eb-8802-969a2e97dcdd.png)
- 쓰레드를 늘리면되는가? : 어차피 cpu를 공유하기때문에 1/n으로 나눈다고 달라지지않는다.
- timeout시간을 늘리면되는가? : 오히려 처리되면 안될것들이 처리되기 위해서 큐에 더 쌓이게된다.

#### 글 작성 요청을 따로 queue에 저장하였다 처리하기 위한 message queue
![화면 캡처 2021-02-13 143720](https://user-images.githubusercontent.com/62214428/107842771-0f933a00-6e09-11eb-91d0-4817aa880176.png)

- 글작성 요청 -> 컨트롤러로 들어온 글 작성에 대한 요청들은 따로 queue에 넣어놓고 쓰레드는 다음 다른 요청을 받을 준비를 한다.
![화면 캡처 2021-02-13 143805](https://user-images.githubusercontent.com/62214428/107842779-18840b80-6e09-11eb-89c0-7250f3fcfb60.png)

- 톰캣의 queue와 다른 점  : 톰캣의 큐보다 저장에 특화된 큐 / 만약 톰캣의 큐는 톰캣이 종료되면(서버가 죽으면) 큐도 사라지고 그 안에 저장된 내용도 당연히 같이 사라진다.

### Message Queue의 장점   
-

**Comment by skarltjr** [comment]
## 글 목록조회 성능 테스트
- 50만건에 대해글 목록조회 테스트하기 
- 워커인스턴스 4개까지 추가해주기 /
-  젠킨스 구성설정 후 배포( 메타데이터로 젠킨스 공개키 설정은 이미 했다. /  시스템 설정에서 젠킨스에서 새로만든 인스턴스 ssh에 접근할 수 있도록 추가 / 프로젝트 구성에서 배포스크립트의 ssh서버 추가
- 이ㅣ 후 배포
![화면 캡처 2021-02-13 220040](https://user-images.githubusercontent.com/62214428/107850600-f14c2f00-6e46-11eb-9184-971c33f6369a.png)


- 이 후 테스트
```
config:
  target: "http://34.64.207.46"
  phases:
    - duration: 60
      arrivalRate: 3
      name: Warm up
    - duration: 120
      arrivalRate: 3
      rampTo: 50
      name: Ramp up load
    - duration: 6000
      arrivalRate: 50
      name: Sustained load
  payload:
    path: "ratings_test_50k.csv"
    fields:
      - "content"
scenarios:
  - name: "just post content"
    flow:
      - post:
          url: "/post"
          json:
            content:  "{{ content }}"
      - think: 1
      - get:
          url: "/posts"      
```

**Comment by skarltjr** [comment]
## nginx에서 connection refuse가 났을 때 
- 확인을 해보니 rabbitmq와 연동된 글 작성에서 오류
- 알고보니 nginx인스턴스에서 rabbitmq 실행 x 
- 도커설치부터 rabbitmq 재연결

**Comment by skarltjr** [comment]
## Elastic Search 
- db와의 차이점

### ES의 문서 저장 방식 / Inverted Index(역 색인)
- db : 직관적 
- 문서 -> 내용
![화면 캡처 2021-02-18 215403](https://user-images.githubusercontent.com/62214428/108359868-de18d500-7233-11eb-81a5-fbdb64f0981c.png)
------------

- ES : 문서- >내용에 추가로 단어 ->문서로 찾을 수 있는 테이블이 추가된다.
- 즉 특정 단어가 포함된 문서를 빠르게 찾을 수 있다. (역 색인)
- 그런데 만약 "재미"라는 단어로 검색하면 여기서는 "재미있다"를 포함한 문서는 검색이 안된다. /한국어는 ES에서 제공하는 플러그인 NORI를 사용하여 형태소 분석
![화면 캡처 2021-02-18 215443](https://user-images.githubusercontent.com/62214428/108359926-ec66f100-7233-11eb-9926-03b252ef5253.png)

### Shard 샤드
- 문서가 1~100까지 있다고 했을 때 이 문서들을 쪼개서 저장
- 왜 중요한가? : 만약 각각의 저장소를 각각의 인스턴스에 올려서 사용하면 효율성 증가
![화면 캡처 2021-02-18 220240](https://user-images.githubusercontent.com/62214428/108360932-300e2a80-7235-11eb-9da6-512d20dc90e5.png)

**Comment by skarltjr** [comment]
## ES를 통해 검색 요청의 성능을 끌어올리자
- 우선 rabbitMQ인스턴스는 삭제
- nginx내부아이피로 접근하며 그렇기때문에 당연히 이전에 nginx인스턴스에서 rabbitMQ에 접근해서 queue를 설정해뒀고 그걸쓰는것. 즉 rabbitMQ인스턴스에서 사용하는게 없다 = 삭제해도된다.
```
 rabbitmq:
    host: 10.178.0.21 / nginx내부아이피
    username: guest
    password: guest
    port: 5672 
```

### 목표 = ES 클러스터를 구축. 4개의 es인스턴스를 마치 하나의 인스턴스처럼 묶어주기
- 지리적으로 가까운 도쿄에 ES인스턴스 4개 설치
- 4개의 인스턴스 ssh로
```
# ES 노드에서 실행해야 할 명령어
# 1. 공통
sudo yum install -y docker
sudo systemctl start docker
sudo chmod 666 /var/run/docker.sock

sudo sysctl -w vm.max_map_count=262144

# 2. 1번 노드에서만 실행시키는 명령어 (인스턴스 IP)
docker network create somenetwork
docker run -d --name elasticsearch --net somenetwork -p 9200:9200 -p 9300:9300 \
-e "discovery.seed_hosts={1번 IP 빼고 나머지 3개 IP} \
-e "node.name=es01" \
-e "cluster.initial_master_nodes=es01,es02,es03,es04" \
-e "network.publish_host={1번 IP} \
elasticsearch:7.10.1

# 3. 2번 노드에서 실행시키는 명령어
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 \
-e "discovery.seed_hosts={2번 IP 빼고 나머지 3개 IP} \
-e "node.name=es02" \
-e "cluster.initial_master_nodes=es01,es02,es03,es04" \
-e "network.publish_host={2번 IP} \
elasticsearch:7.10.1

# 4. 3번 노드에서 실행시키는 명령어
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 \
-e "discovery.seed_hosts={3번 IP 빼고 나머지 3개 IP} \
-e "node.name=es03" \
-e "cluster.initial_master_nodes=es01,es02,es03,es04" \
-e "network.publish_host={3번 IP} \
elasticsearch:7.10.1

# 5. 4번 노드에서 실행시키는 명령어
docker run -d --name elasticsearch -p 9200:9200 -p 9300:9300 \
-e "discovery.seed_hosts={4번 IP 빼고 나머지 3개 IP} \
-e "node.name=es04" \
-e "cluster.initial_master_nodes=es01,es02,es03,es04" \
-e "network.publish_host={4번 IP} \
elasticsearch:7.10.1
```
